    <section class="admin">

        <h1>Administration</h1>

            <h2>Connexion :</h2>
            
            <form method="POST">

                <table align="center">
                    <tr>
                        <td><label>Pseudo:</label></td>
                    </tr>
                    <tr>
                        <td><input type="text" name="username"/></td>
                    </tr>
                    <tr>
                        <td><label>Mot de passe:</label></td>
                    </tr>
                    <tr>
                        <td><input type="password" name="password"/></td>
                    </tr>
                    <tr>
                        <td><input type="submit" name="submit" value='valider' class='btnvalider'/></td>
                    </tr>
                </table>  

                <div>
                    <a href="index.php">Retour sur le site</a> 
                </div>

            </form>

    </section>

