<section class="connexionUser">

    <h1>Connexion :</h1>
    
    <form method="POST">

        <table align="center">
            <tr>
                <td><label>E-mail:</label></td>
            </tr>
            <tr>
                <td><input type="email" name="mail" value="<?php if(isset($mail)) { echo $mail; } ?>"/></td>
            </tr>
            <tr>
                <td><label>Mot de passe:</label></td>
            </tr>
            <tr>
                <td><input type="password" name="password"/></td>
            </tr>
            <tr>
                <td><input type="submit" name="connexion" value='valider' class='btnvalider'/></td>
            </tr>
        </table>  

        <div>
            <a href="../index.php">Retour sur le site</a> 
        </div>

    </form>

</section>

