<!doctype html>
<html lang="fr">
    <head>
        <title>Pizzeria</title>
        <meta charset="utf-8"/>
        <meta name="description" content="Ici la description de mon site"/>
        <link href="https://fonts.googleapis.com/css?family=Lobster|Shrikhand" rel="stylesheet">  
        <link rel="stylesheet" href="css/normalize.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> 
        <link rel="stylesheet" href="css/style.css"/>
    </head>
    
    <body>
        
        <header>
            
            <div class='logo'>
                <a href="index.php">PIZZA'HOUSE</a>
                <img src="images/logo/logo.jpg" alt='logo'>
            </div>
            
        </header>
        
        <main>
            <h1>Supprimer un produit</h1>
            
            <form class="deleteform" methode="post" action="Delete.php" enctype= "multipart/form-data">
                
                <input type='hidden' name='id' value='<?= $id; ?>'/>
                <p>Êtes vous sur de vouloir supprimer?</p>
               
                <button type='submit'>OUI</button>
                <a href='product.phtml'>NON</a>
                
            </form>
            
        </main>
        
    </body>
</html>
   
   
    