<!DOCTYPE html>
<html lang="fr">
    <head>
        <title>Document Titre</title>
        <meta charset="utf-8"/>
        <meta name="description" content="Ici la description de mon site"/>

        <link href="https://fonts.googleapis.com/css?family=Lobster|Shrikhand" rel="stylesheet">  
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> 
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
        
        <link rel="stylesheet" href="css/normalize.css" />
        <link rel="stylesheet" href="css/style.css"/>

        <link rel="stylesheet" href="../css/normalize.css" />
        <link rel="stylesheet" href="../css/style.css"/>

        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="/resources/demos/style.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    </head>
    
<body>
    <header>

        <div class='logo'>
            <a href="index.php">PIZZA'HOUSE</a>
            <img src="images/logo/logo.jpg" alt='logo'>
        </div>


        <?php 
            
            // S' il n'y a pas de session 
            if(!isset($_SESSION['id']) && !isset($connectuser['id']))

            
            {?>


            <!--<div>
                <p><//?php echo $connectuser['nom'];?></p>
            </div> -->
            
            <nav>
                <ul class='menu'>
                    <li><a href='controllers/inscription_user.php'>Inscription</a></li>
                    <li><a href='controllers/connexion_user.php'>Connexion</a></li>
                    <li><a href='lacarte.php'>La carte</a></li>

                </ul>
            </nav>

        <?php }
            
            // S'il ya une session 
        else { ?>

            <nav>
                <ul class='menu'>
                    <li><a href='controllers/deconnexion_user.php'>Déconnexion</a></li>
                    <li><a href='controllers/reservation.php'>Reservation</a></li>
                </ul>
            </nav>
            
            <?php }?>
        
    </header>
