
<main>
    <section class="reservation">
        <h1>Réservez votre Table</h1>
        <form method="post" action="controllers/reservation.php">
            <fieldset>
    
                <script>
                $( function() {
                    $( "#datepicker" ).datepicker();
                } );
                </script>

                <label for="nom">Date :</label>
                <input type="text" name="date" id="datepicker"/>

                <label for="nom" name="heure">Heure :</label>
                <select>
                    <option>12</option>
                    <option>13</option>
                    <option>14</option>
                    <option>19</option>
                    <option>20</option>
                    <option>21</option>
                    <option>22</option>
                    <option>23</option>
                </select>
                
                <label for="nom">Notre Nom :</label>
                <input type='text' name="nom"/>

                <label for="telephone">Téléphone :</label>
                <input type='text' name="telephone"/>

                <label for="personne" name="nombre_personne">Nombre de personnes :</label>
                <select>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                    <option>6</option>
                    <option>7</option>
                    <option>8</option>
                    <option>9</option>
                    <option>10</option>
                </select>
                <input type="submit" name="reservation" value="Réservez" class="btnvalider"/>
            </fieldset>
        </form> 
    </section>

    
        <section class="section3">
                
                <div>
                    <h3>Adresse :</h3>
                    <p>16 rue Albert Camus <br/>60100 Creil</p>
                
                    <h3>Horaires d'ouverture:</h3>
                    <p>Ouvert 7J/7</p>
                    <p>Du lundi à jeudi de 11h00 à 14h30 et de 18h00 à 00h00<br/>Du vendredi à dimanche de 11h00 à 00h00.</p>
                </div>
                
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d20836.209480865957!2d2.4797379!3d49.24747185!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfr!2sfr!4v1528416295529" frameborder="0" style="border:0" allowfullscreen>
                
                </iframe>
            </section>
    </main>