            <section class="inscription">

                <h1>Inscription</h1>
            
                <form method="post" action="">

                    <table align="center">

                        <tr>
                            <td align="right">
                                <label>Nom:</label>  
                            </td>
                            <td>
                                <input type="text" name="nom" value="<?php if(isset($nom)) { echo $nom; } ?>"/>
                            </td>
                        </tr>

                        <tr>
                            <td align="right">
                                <label>Email:</label>  
                            </td>
                            <td>
                                <input type="email" name="mail" value="<?php if(isset($mail)) { echo $mail; } ?>"/>
                            </td>
                        </tr>

                        <tr>
                            <td align="right">
                                <label>Confirmer votre mail:</label>  
                            </td>
                            <td>
                                <input type="email" name="mail2" value="<?php if(isset($mail2)) { echo $mail2; } ?>"/>
                            </td>
                        </tr>
                        
                        <tr>
                            <td align="right">
                                <label>Mot de passe:</label> 
                            </td>

                            <td>
                                <input type="password" name="password"/> 
                            </td>
                        </tr>
                    
                        <tr>
                            <td>
                                <label>Confirmer le mot de passe:</label> 
                            </td>

                            <td>
                                <input type="password" name="password2"/>
                            </td>
                        </tr>
                    </table>  
                    
                    </br>
                    <input type="submit" name="inscription" value="Valider" class="btnvalider"/>

                </form>

                <div>
                    <a href="../index.php"><i class="fas fa-arrow-alt-circle-left"></i></a>
                </div>

            </section>
