        <main>
            <h1>Modifier un produit</h1>
            
            <form class="updateform" methode="post" action=" <?php 'update.php?id=' . $id; ?>" enctype= multipart/form-data>
                
                <label for="name">Nom :</label>
                <input type="text" id="nom" name="nom">
                <span><?= $erreurMessageNom; ?></span>
                
                <label for="description">Description :</label>
                <input type="text" id="description" name="description">
                <span><?= $erreurMessageDescription; ?></span>
                
                <label for="price">Prix :</label>
                <input type="number" step="0.01" id="prix" name="prix">
                <span><?= $erreurMessagePrix; ?></span>
                <br>
                
                <label>Image :</label>
                <p><?= $image; ?></p>
                <label for='image'>Télècharger votre image :</label>
                <input type='file' id='image' name='image'>
                <span><?=  $erreurMessageImg; ?></span>
                <br>
                
                <div class='viewimage'>
                    <img src="<?= '../img/' . $image ; ?>" alt="">
                </div>
                
                <button type='submit'>Modifier</button>
                <a href='product.phtml'>Annuler</a>
                
            </form>
            
        </main>
        
    </body>
</html>