</main>
<footer>

    <div class='footer'>
        <i class="fas fa-phone-square"></i><a href="tel:+33344000000">03 44 00 00 00</a><br/>
        <i class="fas fa-at"></i><a href="mailto:laila86@hotmail.fr">e-mail</a>
        <p>Copyright &copy; Pizzeria 2018</p>  
    </div>

</footer>
     <!--    bootstrap formulaire    -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!--    datepicker   -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="i18n/datepicker-fr.js"></script>

    <script>

        $( function() {
            $( "#datepicker" ).datepicker( $.datepicker.regional[ "fr" ] );
            $( "#datepicker" ).datepicker("dateFormat", "dd/mm/yy");
        } );

    </script>

    <!--    animation h1/home   -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>

    <!--    leaflet map   -->
    <script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
    integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
    crossorigin=""></script>

    <script>

        // Coordonnees latitude et longitude / coordonnées geographiques de la ville
        let loc_geo = [49.266667, 2.483333];

        // Création de la map L- leaflet  
        let map = L.map('map').setView(loc_geo, 15);

        // Création du calque image
        L.tileLayer('https://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}', {
        maxZoom: 20,
        }).addTo(map);

        //Ajout d'un marker
        let marker = L.marker(loc_geo).addTo(map);

        //Ajout d'un popup
        marker.bindPopup("<div class='popup'><h4>Pizza house</h4><img class='imgPopup' src='Images/logo/logo.jpg'></div>"); 

    </script>

        <!-- Les redirections -->
        <?php if(isset($home) && $home === "home"): ?>            
            <script type="text/javascript" src="Js/slider.js"></script>
            <script type="text/javascript" src="Js/main.js"></script> 
        <?php else: ?>
            <script type="text/javascript" src="../Js/slider.js"></script>
            <script type="text/javascript" src="../Js/main.js"></script> 
        <?php endif; ?>    

</body>

</html>