<!DOCTYPE html>
<html lang="fr">
    <head>
        <title>Pizzeria Creil - Pizza house</title>
        <meta charset="utf-8"/>
        <meta name="description" content="Restaurant pizzeria Creil, reservation table"/>

        <!-- Fontawsome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
        

        <!-- Font google -->
        <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet"> 
        
        <!--   CSS   -->
        <?php if(isset($home) && $home === "home"): ?>            
            <link rel="stylesheet" href="css/normalize.css" /> 
            <link rel="stylesheet" href="css/style.css"/>
        <?php else: ?>
            <link rel="stylesheet" href="../css/normalize.css" />
            <link rel="stylesheet" href="../css/style.css"/>
        <?php endif; ?>       
    
        <!--    bootstrap formulaire    -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        
        <!--   date-picker   -->
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->

        <!--   leaflet   -->
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css"
            integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
            crossorigin=""/>
    </head>
    
<body>
    <header id="header">
        <div class='logo'>
            <div><h1>Pizza house</h1></div>

            <!--   Chemins logo   -->
            <?php if(isset($home) && $home === "home"): ?>            
                <div><img src="Images/logo/logo.jpg" alt="logo"></div>
            <?php else: ?>
                <div><img src="../Images/logo/logo.jpg" alt="logo"></div>
            <?php endif; ?>      

        </div>

        <!--   Chemins navigations  -->
        <?php if(isset($home) && $home === "home"): ?>            
            <nav>
                <ul class='navbar'>
                    <li><a href='controllers/inscription_user.php'>Inscription</a></li> 
                    <li><a href='controllers/connexion_user.php'>Connexion</a></li>
                    <li><a href='controllers/lacarte.php'>La carte</a></li>
                </ul>
            </nav> 
        <?php else: ?>
            <nav>
                <ul class='navbar'>
                    <li><a href='../controllers/inscription_user.php'>Inscription</a></li>
                    <li><a href='../controllers/connexion_user.php'>Connexion</a></li>
                    <li><a href='../controllers/lacarte.php'>La carte</a></li>
                </ul>
            </nav>
        <?php endif; ?>       
</header>
<main>
