<!--   Page d'accueil   -->
<main id="home">
    <section>
        <h1 class="ml6">
            <span class="text-wrapper">
                <span class="letters">Connectez vous pour réserver une table</span>
            </span>
        </h1>
    </section>

    <section class='slider'>
        <img name='slider'>
    </section>

    <section class="adresse">
        <div class='container'>          
            <article class='bgdcolor'>
                <h2>Pizza house</h2>
                <p>16 rue Albert Camus </br>60100 Creil</p>
                    
                <h2>Horaires d'ouverture</h2>
                <p>Ouvert 7J/7</p>
                <p>Du lundi à jeudi de 11h00 à 15h et de 18h00 à 00h00</p>
                <p>Du vendredi à dimanche de 11h00 à 00h00.</p>
            </article>
            
            <div id='map'></div>
            
        </div> 
    </section>
</main>


    