
<div class='retour'>
        <a href="../index.php">Retour</a> 
</div>

<!--   Formuliare d'inscription utilisateur   -->
<section id="formulaire">

        <div class="container">
                <h1>Inscription</h1>
                <form method="post" action="inscription_user.php" class='form' enctype="multipart/form-data">
                        <div class="form-group">
                                <label>Nom:</label>
                                <input type="text" class="form-control" name="nom" value="<?php if(isset($nom)) { echo $nom; } ?>"/>
                        </div>
                        <div class="form-group">
                                <label for="name">Email:</label>
                                <input type="email" class="form-control" name="mail" value="<?php if(isset($mail)) { echo $mail; } ?>"/>
                        </div>
                        <div class="form-group">
                                <label for="name">Confirmation Email:</label>
                                <input type="email" class="form-control" name="mail2" value="<?php if(isset($mail2)) { echo $mail2; } ?>"/>
                        </div>
                        <div class="form-group">
                                <label for="prix">Mot de passe:</label>
                                <input type="password" class="form-control" name="password"/> 
                        </div>
                        <div class="form-group">
                                <label for="prix">Confirmation Mot de passe:</label>
                                <input type="password" class="form-control" name="password2"/> 
                        </div>
                                
                        <input type="submit" name="inscription" value="Valider" class="btnvalider"/>
                </form>
        </div>
</section>

