<!--   Formuliare de telechargement   -->
<section id='formulaire'>
        <div class='retour'>
                <a href='../controllers/interface_admin.php'>Retour</a>
        </div>
        <div class="container">
                <h1>Ajouter un produit</h1>
                <form class="form" method="post" action="../controllers/insert_product.php"  enctype="multipart/form-data">
                        <div class="form-group">
                                <label for="image">Télécharger votre image :</label>
                                <input id="image"  name="image" type="file">
                                <span><?= $message ?></span>
                        </div>
                        <div class="form-group">
                                <label for="name">Nom :</label>
                                <input type="text" class="form-control" id="nom" name="nom">
                        </div>
                        <div class="form-group">
                                <label for="prix">Prix:</label>
                                <input type="number" class="form-control" step="0.01" id="prix" name="prix">
                        </div>

                        <div class="form-group">
                                <input type="submit" name="insert" value="Ajouter" class='btnvalider'>
                        </div>
                </form>
        </div>
</section>








