<div class='retour'>
        <a href="../index.php">Retour</a> 
</div>

<!--   Interface utilisateur  -->
<section id="interfaceUser">
        <h1>Bonjour !</h1>
        <div class="user">
                <ul>
                        <li><a href='reservation_table.php'>Réservez votre table</a></li>
                        <li><a href="../controllers/logout_user.php">Déconnexion</a></li>
                </ul>
        </div>
</section>
