<!--   Interface administrateur   -->
<div class='container_admin'><h1 class='h1_admin'>Administration du site</h1></div>
<section id="interfaceAdmin">
        <div class="admin">
                <ul>
                        <li><a href="../controllers/show_product.php">La Carte</a></li>
                        <li><a href="../controllers/list_reservation.php">Liste des réservations</a></li>
                        <li><a href="../controllers/logout_admin.php">Déconnexion</a></li>
                </ul>
        </div>
</section>
