    
<div class='retour'>
    <a href='../controllers/interface_user.php'>Retour</a>
</div>

<!-- Formulaire de reservation de table -->
<section id='formulaire'>
    
    <div class="container">
        <h1>Réservation</h1>
                <form method="POST" class='form' action="../controllers/reservation_table.php"  enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="date">Date :</label>
                            <input type="text" class="form-control" name="date" id="datepicker" required/>

                        </div>
                        <div class="form-group">
                            <label for="heure" name="heure">Heure :</label>
                            <select id="option_heure" name="heure" class="form-control">
                                <option value="12h">12h</option>
                                <option value="13h">13h</option>
                                <option value="14h">14h</option>
                                <option value="19h">19h</option>
                                <option value="20h">20h</option>
                                <option value="21h">21h</option>
                                <option value="22h">22h</option>
                                <option value="23h">23h</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="nom">Votre Nom :</label>
                            <input type='text' class="form-control" name="nom" required/>
                        </div>

                        <div class="form-group">
                            <label for="telephone">Téléphone :</label>
                            <input type='text' class="form-control" name="telephone" maxLength="10" required/>
                        </div>

                        <div class="form-group">
                        <label for="personne"  name="nombre_personne">Nombre de personnes :</label>
                        <select name="nombre_personne" class="form-control" required>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                        </div>

                        <div class="form-group">
                            <input type="submit" class="form-control" name="reservation" value="Réservez" class="valider_reservation"/>       
                        </div>
                </form>
        </div>
</section>
